-- Vedvis Herb product catalog
-- Run this once in the Supabase SQL Editor (Dashboard > SQL Editor > New query).

create table if not exists public.products (
  id              bigint generated by default as identity primary key,
  slug            text unique,
  name            text not null,
  tagline         text        default '',
  category        text        default 'Uncategorised',
  price           numeric(10,2) default 0,
  weight          text        default '',
  description     text        default '',
  long_description text       default '',
  how_to_use      text        default '',
  benefits        text[]      default '{}',
  ingredients     text[]      default '{}',
  image           text        default '',
  rating          numeric(2,1) default 0,
  reviews         integer     default 0,
  sort_order      integer     default 0,
  published       boolean     default true,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

create index if not exists products_sort_order_idx on public.products (sort_order);
create index if not exists products_published_idx   on public.products (published);

-- Keep updated_at honest.
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at
  before update on public.products
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------- security
-- Public visitors may read published products.
alter table public.products enable row level security;

drop policy if exists "products are readable by everyone" on public.products;
create policy "products are readable by everyone"
  on public.products for select
  using (published = true);

-- Writes are restricted to emails listed in public.admins.
--
-- Do NOT use "to authenticated with check (true)" here: that grants write
-- access to every registered account, not just your admin. Anyone who can
-- sign up would be able to delete your catalog.
create table if not exists public.admins (
  email      text primary key,
  created_at timestamptz default now()
);

alter table public.admins enable row level security;

-- SECURITY DEFINER helper. It runs as the table owner, so it bypasses RLS on
-- public.admins. Without this, a policy on admins that queries admins makes
-- Postgres raise "42P17: infinite recursion detected in policy", which breaks
-- every product write.
drop function if exists public.is_admin();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admins where email = auth.jwt() ->> 'email'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "admins can read admins" on public.admins;
create policy "admins can read admins"
  on public.admins for select
  to authenticated
  using (public.is_admin());

-- Add your admin email (change this before running):
insert into public.admins (email) values ('YOUR-EMAIL@example.com')
on conflict (email) do nothing;

drop policy if exists "admins can insert products" on public.products;
create policy "admins can insert products"
  on public.products for insert
  to authenticated
  with check (public.is_admin());

drop policy if exists "admins can update products" on public.products;
create policy "admins can update products"
  on public.products for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "admins can delete products" on public.products;
create policy "admins can delete products"
  on public.products for delete
  to authenticated
  using (public.is_admin());

-- ------------------------------------------------------------------- admin
-- Create the admin account in Dashboard > Authentication > Users > Add user
-- (tick "Auto Confirm User"), using the same email you inserted above.
--
-- Also disable public sign-ups, otherwise anyone can register an account:
--   Dashboard > Authentication > Sign In / Providers > turn off Email
-- See supabase/admin.sql for the SQL alternative.