-- Vedvis Herb product catalog
-- Run this once in the Supabase SQL Editor (Dashboard > SQL Editor > New query).

create table if not exists public.products (
  id              bigint generated by default as identity primary key,
  slug            text unique,
  name            text not null,
  tagline         text        default '',
  category        text        default 'Uncategorised',
  price           numeric(10,2) default 0,
  weight          text        default '',
  description     text        default '',
  long_description text       default '',
  how_to_use      text        default '',
  benefits        text[]      default '{}',
  ingredients     text[]      default '{}',
  image           text        default '',
  rating          numeric(2,1) default 0,
  reviews         integer     default 0,
  sort_order      integer     default 0,
  published       boolean     default true,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

create index if not exists products_sort_order_idx on public.products (sort_order);
create index if not exists products_published_idx   on public.products (published);

-- Keep updated_at honest.
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at
  before update on public.products
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------- security
-- Public visitors may read published products.
alter table public.products enable row level security;

drop policy if exists "products are readable by everyone" on public.products;
create policy "products are readable by everyone"
  on public.products for select
  using (published = true);

-- Writes require the dashboard password entered by an admin.
-- The app turns that password into a Supabase session via signInWithPassword,
-- so writes are allowed only for signed-in admins.
drop policy if exists "admins can insert products" on public.products;
create policy "admins can insert products"
  on public.products for insert
  to authenticated
  with check (true);

drop policy if exists "admins can update products" on public.products;
create policy "admins can update products"
  on public.products for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "admins can delete products" on public.products;
create policy "admins can delete products"
  on public.products for delete
  to authenticated
  using (true);

-- ------------------------------------------------------------------- admin
-- One admin account. Create it in Dashboard > Authentication > Users > Add user
-- (tick "Auto Confirm User"), then set a password. Use that email + password
-- in the dashboard login screen.