import { createContext, useContext, useState, useCallback } from 'react'

const translations = {
  en: {
    // Navbar
    navHome: 'Home',
    navProducts: 'Products',
    navAbout: 'About',
    navWhyUs: 'Why Us',
    navContact: 'Contact',
    navCta: 'Get in Touch',

    // Hero
    heroBadge: 'Ancient Wisdom, Modern Wellness',
    heroTitle1: 'Pure',
    heroTitle2: 'Ayurvedic',
    heroTitle3: 'Healing',
    heroSub: "Handcrafted from nature's finest ingredients, rooted in centuries-old Ayurvedic traditions. Restore your balance, naturally.",
    heroCta1: 'Explore Products',
    heroCta2: 'Our Story',
    heroScroll: 'Scroll',

    // Ticker
    ticker1: '🌿 100% Natural',
    ticker2: '✦ Lab Tested',
    ticker3: '🌱 Organic Certified',
    ticker4: '💛 Handcrafted with Care',
    ticker5: '🕉 Ancient Formulations',
    ticker6: '🚚 Free Shipping 999+',
    ticker7: '♻ Sustainable Sourcing',
    ticker8: '🏆 Trusted by 50K+',

    // Products
    productsBadge: 'Our Collection',
    productsTitle1: "Nature's Finest",
    productsTitle2: 'Healing Remedies',
    productsSub: 'Every product is a promise — pure ingredients, traditional formulations, and the healing power of Ayurveda.',
    productsLearnMore: 'Learn More',

    // About
    aboutBadge: 'Our Story',
    aboutTitle1: 'Rooted in Tradition,',
    aboutTitle2: 'Crafted for Today',
    aboutP1: "Vedvis Herb was born from a deep reverence for Ayurveda — the ancient Indian science of life. Our founder grew up watching grandmother's remedies heal entire villages using nothing but herbs from their garden.",
    aboutP2: "Today, we bridge the gap between that timeless wisdom and modern wellness needs. Every product in our line is a tribute to those healing traditions, made with ingredients you can trust and formulations that deliver real results.",
    aboutP3: "We believe that true wellness comes from harmony — between body, mind, and nature. That's why every step of our process honors both ancient practice and modern science.",
    aboutStat1Val: '15+',
    aboutStat1Label: 'Years of Trust',
    aboutStat2Val: '50K+',
    aboutStat2Label: 'Happy Customers',
    aboutStat3Val: '100%',
    aboutStat3Label: 'Pure Ingredients',
    aboutValue1Title: '100% Natural',
    aboutValue1Desc: 'Every ingredient is sourced directly from nature, free from synthetic chemicals and additives.',
    aboutValue2Title: 'Lab Tested',
    aboutValue2Desc: 'Rigorous quality testing ensures purity, potency, and safety in every batch we produce.',
    aboutValue3Title: 'Made with Love',
    aboutValue3Desc: 'Handcrafted in small batches with care, following centuries-old Ayurvedic wisdom.',
    aboutValue4Title: 'Sustainably Sourced',
    aboutValue4Desc: 'Ethically harvested ingredients that support local farmers and protect biodiversity.',

    // Why Us
    whyBadge: 'Why Vedvis Herb',
    whyTitle1: 'The Vedvis Herb',
    whyTitle2: ' Promise',
    whySub: "We don't just sell products — we deliver trust, quality, and a commitment to your holistic well-being.",
    whyReason1Title: 'Certified Organic',
    whyReason1Desc: 'All products carry organic certification from recognized authorities.',
    whyReason2Title: 'Free Shipping',
    whyReason2Desc: 'Free delivery on orders above ₹999. Swift dispatch within 24 hours.',
    whyReason3Title: '30-Day Returns',
    whyReason3Desc: 'Not satisfied? Return within 30 days for a complete refund.',
    whyReason4Title: 'Expert Guidance',
    whyReason4Desc: 'Our Ayurvedic experts are available for personalized wellness consultations.',
    whyTestBadge: 'Testimonials',
    whyTestTitle: 'Loved by Thousands',
    whyTest1Text: 'The Triphala powder has transformed my digestion. I feel lighter and more energetic than ever. Vedvis Herb products are truly authentic.',
    whyTest1Name: 'Priya Sharma',
    whyTest1Role: 'Yoga Instructor',
    whyTest2Text: 'Ashwagandha capsules helped me manage work stress naturally. No more sleepless nights. Highly recommend for anyone with a demanding schedule.',
    whyTest2Name: 'Rajesh Gupta',
    whyTest2Role: 'Software Engineer',
    whyTest3Text: 'My entire family uses Vedvis Herb products. The Brahmi hair oil has made my hair so much stronger. Trustworthy quality every time.',
    whyTest3Name: 'Meera Patel',
    whyTest3Role: 'Home Maker',

    // Contact
    contactBadge: 'Get in Touch',
    contactTitle1: "Let's Start Your",
    contactTitle2: 'Wellness Journey',
    contactSub: "Have questions about our products or need personalized Ayurvedic advice? We're here to help you find the right path to natural wellness.",
    contactPhone: '+91 98765 43210',
    contactPhoneSub: 'Mon - Sat, 9am to 6pm',
    contactEmail: 'hello@vedvisherb.com',
    contactEmailSub: 'We reply within 24 hours',
    contactAddr: 'Mumbai, Maharashtra, India',
    contactAddrSub: 'Visit our experience center',
    contactWa: 'WhatsApp Us',
    contactWaSub: 'Quick responses via WhatsApp',
    contactName: 'Full Name',
    contactNamePh: 'Your name',
    contactEmailLabel: 'Email',
    contactEmailPh: 'you@example.com',
    contactPhoneLabel: 'Phone',
    contactPhonePh: '+91 98765 43210',
    contactSubject: 'Subject',
    contactSubjectDefault: 'Select a topic',
    contactSubject1: 'Product Inquiry',
    contactSubject2: 'Ayurvedic Consultation',
    contactSubject3: 'Order Support',
    contactSubject4: 'Wholesale / Bulk',
    contactSubject5: 'Other',
    contactMsg: 'Message',
    contactMsgPh: 'Tell us how we can help you...',
    contactSend: 'Send Message',

    // Footer
    footerDesc: 'Pure Ayurvedic wellness products, crafted with love and ancient wisdom.',
    footerNewsletter: 'Join Our Wellness Community',
    footerNewsletterSub: 'Get early access to new products, Ayurvedic tips, and exclusive offers.',
    footerEmailPh: 'Enter your email',
    footerSubscribe: 'Subscribe',
    footerProd: 'Products',
    footerCompany: 'Company',
    footerSupport: 'Support',
    footerWellness: 'Wellness',
    footerCopyright: '© {year} Vedvis Herb. All rights reserved.',
    footerPrivacy: 'Privacy Policy',
    footerTerms: 'Terms of Service',
    footerCookies: 'Cookie Policy',

    // Products data
    prod1Name: 'Triphala Powder',
    prod1Tag: 'Digestive Wellness',
    prod1Desc: "A powerful blend of three ancient fruits — Amla, Haritaki, and Bibhitaki. Supports digestion and natural detoxification.",
    prod2Name: 'Ashwagandha Capsules',
    prod2Tag: 'Stress Relief',
    prod2Desc: 'Premium KSM-66 Ashwagandha root extract for stress relief, energy boost, and balanced cortisol levels.',
    prod3Name: 'Brahmi Hair Oil',
    prod3Tag: 'Hair Nourishment',
    prod3Desc: 'Infused with Brahmi and Bhringraj herbs, this oil deeply nourishes the scalp and strengthens hair from root to tip.',
    prod4Name: 'Aloe Vera Gel',
    prod4Tag: 'Skin Rejuvenation',
    prod4Desc: 'Pure Aloe Vera gel with turmeric extract for glowing, hydrated skin. Multi-purpose natural skincare solution.',
    prod5Name: 'Turmeric Latte Mix',
    prod5Tag: 'Immunity Booster',
    prod5Desc: 'Golden milk blend with organic turmeric, black pepper, cinnamon, and cardamom. Warm, healing, and delicious.',
    prod6Name: 'Neem Face Wash',
    prod6Tag: 'Deep Cleansing',
    prod6Desc: 'Gentle herbal face wash with neem and tea tree oil. Purifies skin, unclogs pores, and controls excess oil.',
    prod7Name: 'Giloy Juice',
    prod7Tag: 'Immunity Defense',
    prod7Desc: "Fresh pressed Giloy stem juice — nature's immunity powerhouse. Helps fight infections and boosts metabolism.",
    prod8Name: 'Moringa Capsules',
    prod8Tag: 'Superfood Nutrition',
    prod8Desc: 'Concentrated Moringa leaf capsules packed with vitamins, minerals, and antioxidants for overall vitality.',

    // Footer links
    ftLinkProd1: 'Triphala Powder',
    ftLinkProd2: 'Ashwagandha Capsules',
    ftLinkProd3: 'Brahmi Hair Oil',
    ftLinkProd4: 'Giloy Juice',
    ftLinkProd5: 'Turmeric Latte',
    ftLinkComp1: 'About Us',
    ftLinkComp2: 'Our Story',
    ftLinkComp3: 'Quality Promise',
    ftLinkComp4: 'Sustainability',
    ftLinkComp5: 'Careers',
    ftLinkSup1: 'Contact Us',
    ftLinkSup2: 'FAQs',
    ftLinkSup3: 'Shipping Policy',
    ftLinkSup4: 'Return Policy',
    ftLinkSup5: 'Track Order',
    ftLinkWell1: 'Ayurveda Guide',
    ftLinkWell2: 'Health Blog',
    ftLinkWell3: 'Ingredient Glossary',
    ftLinkWell4: 'Dosha Quiz',
    ftLinkWell5: 'Recipes',
  },

  mr: {
    // Navbar
    navHome: 'मुख्यपृष्ठ',
    navProducts: 'उत्पादने',
    navAbout: 'आमच्याबद्दल',
    navWhyUs: 'का आम्हाला निवडावे',
    navContact: 'संपर्क',
    navCta: 'संपर्क करा',

    // Hero
    heroBadge: 'प्राचीन ज्ञान, आधुनिक निरोगीता',
    heroTitle1: 'शुद्ध',
    heroTitle2: 'आयुर्वेदिक',
    heroTitle3: 'उपचार',
    heroSub: 'निसर्गाच्या सर्वोत्तम घटकांपासून हस्तनिर्मित, शतकांपुराण्या आयुर्वेदिक परंपरांवर आधारित. तुमचे संतुलन नैसर्गिकरित्या पुनर्संचयित करा.',
    heroCta1: 'उत्पादने पहा',
    heroCta2: 'आमची कथा',
    heroScroll: 'स्क्रोल करा',

    // Ticker
    ticker1: '🌿 १००% नैसर्गिक',
    ticker2: '✦ लॅब चाचणी केलेले',
    ticker3: '🌱 सेंद्रिय प्रमाणित',
    ticker4: '💛 प्रेमाने हस्तनिर्मित',
    ticker5: '🕉 प्राचीन सूत्रे',
    ticker6: '🚚 ₹९९ॹ वर मोफत वितरण',
    ticker7: '♻ शाश्वत स्रोत',
    ticker8: '🏆 ५० हून अधिक हजार विश्वासार्ह',

    // Products
    productsBadge: 'आमची उत्पादने',
    productsTitle1: 'निसर्गाचे',
    productsTitle2: 'उत्तम उपचार',
    productsSub: 'प्रत्येक उत्पादन हा एक वचन आहे — शुद्ध घटक, पारंपरिक सूत्रे, आणि आयुर्वेदाची उपचार शक्ती.',
    productsLearnMore: 'अधिक जाणून घ्या',

    // About
    aboutBadge: 'आमची कथा',
    aboutTitle1: 'परंपरेत मुळे,',
    aboutTitle2: 'आजसाठी तयार',
    aboutP1: 'वेडव्हिस हर्बचा जन्म आयुर्वेदाप्रतील खोल आदरभावातून झाला — भारताच्या प्राचीन जीवन विज्ञानातून. आमच्या संस्थापकांना आजीच्या औषधांनी गावच्या गावांना बरे करताने बाळपणी पाहिले.',
    aboutP2: 'आज, आम्ही त्या कालातीत ज्ञान आणि आधुनिक निरोगीता गरजांमध्ये फरक भरतो. आमच्या उत्पादनांच्या पंक्तीतील प्रत्येक उत्पादन त्या उपचार परंपरांचे आदर स्वरूप आहे.',
    aboutP3: 'आम्हाला विश्वास आहे की खरी निरोगीता सामंजस्यातून येते — शरीर, मन आणि निसर्ग यांच्यातील सामंजस्यातून.',
    aboutStat1Val: '१५+',
    aboutStat1Label: 'विश्वासाचे वर्षे',
    aboutStat2Val: '५० हजार+',
    aboutStat2Label: 'समाधानी ग्राहक',
    aboutStat3Val: '१००%',
    aboutStat3Label: 'शुद्ध घटक',
    aboutValue1Title: '१००% नैसर्गिक',
    aboutValue1Desc: 'प्रत्येक घटक निसर्गाकडून थेट घेतला जातो, सिंथेटिक रसायने आणि मिश्रणांमुक्त.',
    aboutValue2Title: 'लॅब चाचणी केलेले',
    aboutValue2Desc: 'कडक गुणवत्ता चाचणी प्रत्येक बॅचमध्ये शुद्धता, शक्ती आणि सुरक्षा सुनिश्चित करते.',
    aboutValue3Title: 'प्रेमाने बनवलेले',
    aboutValue3Desc: 'शतकांपुराण्या आयुर्वेदिक ज्ञानाचे पालन करता लहान बॅचेसमध्ये काळजीपूर्वक हस्तनिर्मित.',
    aboutValue4Title: 'शाश्वत स्रोत',
    aboutValue4Desc: 'नैतिकरित्या कापण केलेले घटक जे स्थानिक शेतकऱ्यांना समर्थन देतात आणि जैवविविधता संरक्षित करतात.',

    // Why Us
    whyBadge: 'वेडव्हिस हर्ब का निवडावे',
    whyTitle1: 'वेडव्हिस हर्बचे',
    whyTitle2: ' वचन',
    whySub: 'आम्ही फक्त उत्पादने विकत नाही — आम्ही विश्वास, गुणवत्ता आणि तुमच्या सर्वांगीण कल्याणाची प्रतिबद्धता देतो.',
    whyReason1Title: 'प्रमाणित सेंद्रिय',
    whyReason1Desc: 'सर्व उत्पादनांना मान्यताप्राप्त प्राधिकरणांकडून सेंद्रिय प्रमाणपत्र आहे.',
    whyReason2Title: 'मोफत वितरण',
    whyReason2Desc: '₹९९९ वरील ऑर्डरवर मोफत डिलिव्हरी. २४ तासांच्या आत जलद प्रेषण.',
    whyReason3Title: '३० दिवस परतावा',
    whyReason3Desc: 'समाधान नाही? ३० दिवसांच्या आत पूर्ण परतावा मिळवा.',
    whyReason4Title: 'तज्ञ मार्गदर्शन',
    whyReason4Desc: 'आमचे आयुर्वेदिक तज्ञ वैयक्तिकृत निरोगीता सल्ला देण्यासाठी उपलब्ध आहेत.',
    whyTestBadge: 'प्रशंसापत्रे',
    whyTestTitle: 'हजारो लोकांचे आवडते',
    whyTest1Text: 'त्रिफला पावडरने माझे पचन बदलले. मी आधीपेक्षा हलका आणि अधिक ऊर्जावान वाटतो. वेडव्हिस हर्ब उत्पादने खरोखर प्रामाणिक आहेत.',
    whyTest1Name: 'प्रिया शर्मा',
    whyTest1Role: 'योग प्रशिक्षक',
    whyTest2Text: 'अश्वगंधा कॅप्सूल्सने मला कामाचा ताण नैसर्गिकरित्या व्यवस्थापित करण्यात मदत केली. आता झोप न येण्याचे रात्र नाहीत.',
    whyTest2Name: 'राजेश गुप्ता',
    whyTest2Role: 'सॉफ्टवेअर इंजिनिअर',
    whyTest3Text: 'माझा संपूर्ण कुटुंब वेडव्हिस हर्ब उत्पादने वापरतो. ब्राह्मी केस तेलाने माझे केस खूप मजबूत केले आहेत.',
    whyTest3Name: 'मीरा पटेल',
    whyTest3Role: 'गृहिणी',

    // Contact
    contactBadge: 'संपर्क करा',
    contactTitle1: 'चला तुमची सुरू करूया',
    contactTitle2: 'निरोगीता प्रवास',
    contactSub: 'आमच्या उत्पादनांबद्दल प्रश्न आहेत किंवा वैयक्तिकृत आयुर्वेदिक सल्ला लागते? आम्ही तुम्हाला नैसर्गिक निरोगीतेच्या योग्य मार्गाशी जोडण्यासाठी इथे आहोत.',
    contactPhone: '+९१ ९८७६५ ४३२१०',
    contactPhoneSub: 'सोम - शनि, सकाळी ९ ते सायंकाळी ६',
    contactEmail: 'hello@vedvisherb.com',
    contactEmailSub: 'आम्ही २४ तासांच्या आत उत्तर देतो',
    contactAddr: 'मुंबई, महाराष्ट्र, भारत',
    contactAddrSub: 'आमचे अनुभव केंद्र भेट द्या',
    contactWa: 'व्हॉट्सअॅपवर संपर्क करा',
    contactWaSub: 'व्हॉट्सअॅपवर जलद प्रतिसाद',
    contactName: 'पूर्ण नाव',
    contactNamePh: 'तुमचे नाव',
    contactEmailLabel: 'ईमेल',
    contactEmailPh: 'tumcha@email.com',
    contactPhoneLabel: 'फोन',
    contactPhonePh: '+९१ ९८७६५ ४३२१०',
    contactSubject: 'विषय',
    contactSubjectDefault: 'एक विषय निवडा',
    contactSubject1: 'उत्पादन चौकशी',
    contactSubject2: 'आयुर्वेदिक सल्ला',
    contactSubject3: 'ऑर्डर सहाय्य',
    contactSubject4: 'थोक / मोठ्या प्रमाणात',
    contactSubject5: 'इतर',
    contactMsg: 'संदेश',
    contactMsgPh: 'आम्ही तुम्हाला कशी मदत करू शकतो ते सांगा...',
    contactSend: 'संदेश पाठवा',

    // Footer
    footerDesc: 'शुद्ध आयुर्वेदिक निरोगीता उत्पादने, प्रेम आणि प्राचीन ज्ञानाने तयार.',
    footerNewsletter: 'आमच्या निरोगीता समुदायात सामील व्हा',
    footerNewsletterSub: 'नवीन उत्पादने, आयुर्वेदिक टिपा आणि विशेष ऑफर्समध्ये प्रारंभिक प्रवेश मिळवा.',
    footerEmailPh: 'तुमचा ईमेल प्रविष्ट करा',
    footerSubscribe: 'सदस्यत्व घ्या',
    footerProd: 'उत्पादने',
    footerCompany: 'कंपनी',
    footerSupport: 'सहाय्य',
    footerWellness: 'निरोगीता',
    footerCopyright: '© {year} वेडव्हिस हर्ब. सर्व हक्क राखीव.',
    footerPrivacy: 'गोपनीयता धोरण',
    footerTerms: 'सेवा अटी',
    footerCookies: 'कुकी धोरण',

    // Products data
    prod1Name: 'त्रिफला पावडर',
    prod1Tag: 'पचन निरोगीता',
    prod1Desc: 'तीन प्राचीन फळांचे शक्तिशाली मिश्रण — आवळा, हिरडा आणि बिहितका. पचन आणि नैसर्गिक विषनिवारणाला समर्थन.',
    prod2Name: 'अश्वगंधा कॅप्सूल्स',
    prod2Tag: 'ताण निवारण',
    prod2Desc: 'प्रीमियम KSM-66 अश्वगंधा मुळ अर्क — ताण निवारण, ऊर्जा वाढ आणि संतुलित कोर्टिसॉल पातळी.',
    prod3Name: 'ब्राह्मी केस तेल',
    prod3Tag: 'केस पोषण',
    prod3Desc: 'ब्राह्मी आणि भृंगराज वनस्पतींनी समृद्ध, हे तेल कुशीत खोलीला पोषण देते आणि केस मुळापासून टोपापर्यंत मजबूत करते.',
    prod4Name: 'अॅलोव्हेरा जेल',
    prod4Tag: 'त्वचा कायाकल्प',
    prod4Desc: 'चमकदार, दमट त्वचेसाठी शुद्ध अॅलोव्हेरा जेल हळद अर्कसह. बहुउद्देशीय नैसर्गिक त्वचा काळजी उपाय.',
    prod5Name: 'हळद लॅटे मिक्स',
    prod5Tag: 'रोगप्रतिकारक',
    prod5Desc: 'सेंद्रिय हळद, काळी मिरी, दालचिनी आणि वेलची यांचे सोनेरी दुधे मिश्रण. उबदार, उपचारात्मक आणि स्वादिष्ट.',
    prod6Name: 'नीम फेस वॉश',
    prod6Tag: 'खोल स्वच्छता',
    prod6Desc: 'नीम आणि टी ट्री तेलासह मऊ हर्बल फेस वॉश. त्वचा स्वच्छ करते, छिद्रे उघडते आणि अतिरिक्त तेल नियंत्रित करते.',
    prod7Name: 'गिलोय रस',
    prod7Tag: 'रोगप्रतिकारक संरक्षण',
    prod7Desc: 'ताजा गिलोय मुळाचा रस — निसर्गाची रोगप्रतिकारक शक्ती. संसर्गांशी लढण्यास आणि चयापचय वाढवण्यास मदत.',
    prod8Name: 'मोरिंगा कॅप्सूल्स',
    prod8Tag: 'सुपरफूड पोषण',
    prod8Desc: 'एकूण जीवनशक्तीसाठी व्हिटॅमिन्स, खनिजे आणि अँटीऑक्सिडंट्सनी भरलेले केंद्रित मोरिंगा पानांचे कॅप्सूल्स.',

    // Footer links
    ftLinkProd1: 'त्रिफला पावडर',
    ftLinkProd2: 'अश्वगंधा कॅप्सूल्स',
    ftLinkProd3: 'ब्राह्मी केस तेल',
    ftLinkProd4: 'गिलोय रस',
    ftLinkProd5: 'हळद लॅटे',
    ftLinkComp1: 'आमच्याबद्दल',
    ftLinkComp2: 'आमची कथा',
    ftLinkComp3: 'गुणवत्ता वचन',
    ftLinkComp4: 'शाश्वतपणा',
    ftLinkComp5: 'करिअर',
    ftLinkSup1: 'संपर्क करा',
    ftLinkSup2: 'वारंवार विचारले जाणारे प्रश्न',
    ftLinkSup3: 'शिपिंग धोरण',
    ftLinkSup4: 'परतावा धोरण',
    ftLinkSup5: 'ऑर्डर ट्रॅक करा',
    ftLinkWell1: 'आयुर्वेद मार्गदर्शक',
    ftLinkWell2: 'आरोग्य ब्लॉग',
    ftLinkWell3: 'घटक शब्दकोश',
    ftLinkWell4: 'दोष चाचणी',
    ftLinkWell5: 'करमंडळे',
  },
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')

  const toggleLanguage = useCallback(() => {
    setLang((prev) => (prev === 'en' ? 'mr' : 'en'))
  }, [])

  const t = useCallback(
    (key) => {
      const val = translations[lang]?.[key]
      if (val && typeof val === 'string') {
        return val.replace('{year}', new Date().getFullYear())
      }
      return translations.en?.[key] || key
    },
    [lang]
  )

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
